Revert "CI: LLVM 21"
This reverts commit 66284d0e1568fda3ccd519e00b5abf902a732a34.

GoogleTest 1.17.0 can't handle LLVM 21
dquote>
dquote> gtest-printers.h:528:35: error: implicit conversion from 'char8_t' to 'char32_t' may change the meaning of the represented code unit [-Werror,-Wcharacter-conversion]"